module.exports = {
    trip: [
      'intro'
    ],
    // api: [
    //   'tutorial-basics/congratulations',
    //   {
    //     type: 'category',
    //     label: 'JavaScript',
    //     collapsed: false,
    //     items:[{
    //         type: 'autogenerated',
    //         dirName: 'tutorial-basics', // Generate sidebar slice from docs/api
    //       }],
    //   },
    // ],
    frontEnd:[
      'front-end/intro'
    ],
    backEnd:[
      'back-end/intro'
    ],
    ops:[
      'ops/intro'
    ],
    other:[
      'other/intro'
    ],
    computerScience:[
      'computer-science/intro'
    ],
  };