module.exports = {
  trip: ["intro"],
  // api: [
  //   'tutorial-basics/congratulations',
  //   {
  //     type: 'category',
  //     label: 'JavaScript',
  //     collapsed: false,
  //     items:[{
  //         type: 'autogenerated',
  //         dirName: 'tutorial-basics', // Generate sidebar slice from docs/api
  //       }],
  //   },
  // ],
  web: [
    "web/intro",
    {
      type: "category",
      label: "vue",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "web/vue",
        },
      ],
    },
    {
      type: "category",
      label: "react",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "web/react",
        },
      ],
    },
  ],
  other: ["other/intro"],
  computerScience: ["computer-science/intro"],
};
